-- 6개: ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
-- 1) ANIMAL_ID 출력 + 이름 있는 동물의
-- 2) ID는 오름차순 정렬
SELECT ANIMAL_ID FROM ANIMAL_INS 
WHERE NAME IS NOT NULL 
ORDER BY ANIMAL_ID;